spring:
  application:
    name: customer
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  port: 8080